[default]
    locale = "en-us"

    [default.extend-words]
        nd = "nd"

# Add words to the dictionary from the common misspellings list
[files]
    extend-exclude = ["*_cache", ".cache", ".venv", "tmp"]
